/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapEnDotxmlRouteImport } from './routes/sitemap-en[.]xml'
import { Route as SitemapArDotxmlRouteImport } from './routes/sitemap-ar[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as Char123LangChar125IndexRouteImport } from './routes/{-$lang}/index'
import { Route as Char123LangChar125TermsRouteImport } from './routes/{-$lang}/terms'
import { Route as Char123LangChar125ProductsRouteImport } from './routes/{-$lang}/products'
import { Route as Char123LangChar125CheckoutRouteImport } from './routes/{-$lang}/checkout'
import { Route as Char123LangChar125CartRouteImport } from './routes/{-$lang}/cart'
import { Route as Char123LangChar125BlogRouteImport } from './routes/{-$lang}/blog'
import { Route as Char123LangChar125AccountRouteImport } from './routes/{-$lang}/account'
import { Route as Char123LangChar125ProductsIndexRouteImport } from './routes/{-$lang}/products.index'
import { Route as Char123LangChar125BlogIndexRouteImport } from './routes/{-$lang}/blog.index'
import { Route as Char123LangChar125AccountIndexRouteImport } from './routes/{-$lang}/account.index'
import { Route as Char123LangChar125ProductsProductIdRouteImport } from './routes/{-$lang}/products.$productId'
import { Route as Char123LangChar125CheckoutReturnRouteImport } from './routes/{-$lang}/checkout_.return'
import { Route as Char123LangChar125BlogSlugRouteImport } from './routes/{-$lang}/blog.$slug'
import { Route as Char123LangChar125AccountWishlistRouteImport } from './routes/{-$lang}/account.wishlist'
import { Route as Char123LangChar125AccountRegisterRouteImport } from './routes/{-$lang}/account.register'
import { Route as Char123LangChar125AccountLoginRouteImport } from './routes/{-$lang}/account.login'
import { Route as Char123LangChar125AccountForgotPasswordRouteImport } from './routes/{-$lang}/account.forgot-password'
import { Route as Char123LangChar125AccountOrdersOrderIdRouteImport } from './routes/{-$lang}/account.orders.$orderId'
import { Route as ApiPublicWebhooksPaypalRouteImport } from './routes/api/public/webhooks/paypal'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapEnDotxmlRoute = SitemapEnDotxmlRouteImport.update({
  id: '/sitemap-en.xml',
  path: '/sitemap-en.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapArDotxmlRoute = SitemapArDotxmlRouteImport.update({
  id: '/sitemap-ar.xml',
  path: '/sitemap-ar.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125IndexRoute = Char123LangChar125IndexRouteImport.update({
  id: '/{-$lang}/',
  path: '/{-$lang}/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125TermsRoute = Char123LangChar125TermsRouteImport.update({
  id: '/{-$lang}/terms',
  path: '/{-$lang}/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125ProductsRoute =
  Char123LangChar125ProductsRouteImport.update({
    id: '/{-$lang}/products',
    path: '/{-$lang}/products',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LangChar125CheckoutRoute =
  Char123LangChar125CheckoutRouteImport.update({
    id: '/{-$lang}/checkout',
    path: '/{-$lang}/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LangChar125CartRoute = Char123LangChar125CartRouteImport.update({
  id: '/{-$lang}/cart',
  path: '/{-$lang}/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125BlogRoute = Char123LangChar125BlogRouteImport.update({
  id: '/{-$lang}/blog',
  path: '/{-$lang}/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125AccountRoute =
  Char123LangChar125AccountRouteImport.update({
    id: '/{-$lang}/account',
    path: '/{-$lang}/account',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LangChar125ProductsIndexRoute =
  Char123LangChar125ProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LangChar125ProductsRoute,
  } as any)
const Char123LangChar125BlogIndexRoute =
  Char123LangChar125BlogIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LangChar125BlogRoute,
  } as any)
const Char123LangChar125AccountIndexRoute =
  Char123LangChar125AccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LangChar125AccountRoute,
  } as any)
const Char123LangChar125ProductsProductIdRoute =
  Char123LangChar125ProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => Char123LangChar125ProductsRoute,
  } as any)
const Char123LangChar125CheckoutReturnRoute =
  Char123LangChar125CheckoutReturnRouteImport.update({
    id: '/{-$lang}/checkout_/return',
    path: '/{-$lang}/checkout/return',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LangChar125BlogSlugRoute =
  Char123LangChar125BlogSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => Char123LangChar125BlogRoute,
  } as any)
const Char123LangChar125AccountWishlistRoute =
  Char123LangChar125AccountWishlistRouteImport.update({
    id: '/wishlist',
    path: '/wishlist',
    getParentRoute: () => Char123LangChar125AccountRoute,
  } as any)
const Char123LangChar125AccountRegisterRoute =
  Char123LangChar125AccountRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => Char123LangChar125AccountRoute,
  } as any)
const Char123LangChar125AccountLoginRoute =
  Char123LangChar125AccountLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => Char123LangChar125AccountRoute,
  } as any)
const Char123LangChar125AccountForgotPasswordRoute =
  Char123LangChar125AccountForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => Char123LangChar125AccountRoute,
  } as any)
const Char123LangChar125AccountOrdersOrderIdRoute =
  Char123LangChar125AccountOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => Char123LangChar125AccountRoute,
  } as any)
const ApiPublicWebhooksPaypalRoute = ApiPublicWebhooksPaypalRouteImport.update({
  id: '/api/public/webhooks/paypal',
  path: '/api/public/webhooks/paypal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-ar.xml': typeof SitemapArDotxmlRoute
  '/sitemap-en.xml': typeof SitemapEnDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$lang}/account': typeof Char123LangChar125AccountRouteWithChildren
  '/{-$lang}/blog': typeof Char123LangChar125BlogRouteWithChildren
  '/{-$lang}/cart': typeof Char123LangChar125CartRoute
  '/{-$lang}/checkout': typeof Char123LangChar125CheckoutRoute
  '/{-$lang}/products': typeof Char123LangChar125ProductsRouteWithChildren
  '/{-$lang}/terms': typeof Char123LangChar125TermsRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/account/forgot-password': typeof Char123LangChar125AccountForgotPasswordRoute
  '/{-$lang}/account/login': typeof Char123LangChar125AccountLoginRoute
  '/{-$lang}/account/register': typeof Char123LangChar125AccountRegisterRoute
  '/{-$lang}/account/wishlist': typeof Char123LangChar125AccountWishlistRoute
  '/{-$lang}/blog/$slug': typeof Char123LangChar125BlogSlugRoute
  '/{-$lang}/checkout/return': typeof Char123LangChar125CheckoutReturnRoute
  '/{-$lang}/products/$productId': typeof Char123LangChar125ProductsProductIdRoute
  '/{-$lang}/account/': typeof Char123LangChar125AccountIndexRoute
  '/{-$lang}/blog/': typeof Char123LangChar125BlogIndexRoute
  '/{-$lang}/products/': typeof Char123LangChar125ProductsIndexRoute
  '/api/public/webhooks/paypal': typeof ApiPublicWebhooksPaypalRoute
  '/{-$lang}/account/orders/$orderId': typeof Char123LangChar125AccountOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-ar.xml': typeof SitemapArDotxmlRoute
  '/sitemap-en.xml': typeof SitemapEnDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$lang}/cart': typeof Char123LangChar125CartRoute
  '/{-$lang}/checkout': typeof Char123LangChar125CheckoutRoute
  '/{-$lang}/terms': typeof Char123LangChar125TermsRoute
  '/{-$lang}': typeof Char123LangChar125IndexRoute
  '/{-$lang}/account/forgot-password': typeof Char123LangChar125AccountForgotPasswordRoute
  '/{-$lang}/account/login': typeof Char123LangChar125AccountLoginRoute
  '/{-$lang}/account/register': typeof Char123LangChar125AccountRegisterRoute
  '/{-$lang}/account/wishlist': typeof Char123LangChar125AccountWishlistRoute
  '/{-$lang}/blog/$slug': typeof Char123LangChar125BlogSlugRoute
  '/{-$lang}/checkout/return': typeof Char123LangChar125CheckoutReturnRoute
  '/{-$lang}/products/$productId': typeof Char123LangChar125ProductsProductIdRoute
  '/{-$lang}/account': typeof Char123LangChar125AccountIndexRoute
  '/{-$lang}/blog': typeof Char123LangChar125BlogIndexRoute
  '/{-$lang}/products': typeof Char123LangChar125ProductsIndexRoute
  '/api/public/webhooks/paypal': typeof ApiPublicWebhooksPaypalRoute
  '/{-$lang}/account/orders/$orderId': typeof Char123LangChar125AccountOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-ar.xml': typeof SitemapArDotxmlRoute
  '/sitemap-en.xml': typeof SitemapEnDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$lang}/account': typeof Char123LangChar125AccountRouteWithChildren
  '/{-$lang}/blog': typeof Char123LangChar125BlogRouteWithChildren
  '/{-$lang}/cart': typeof Char123LangChar125CartRoute
  '/{-$lang}/checkout': typeof Char123LangChar125CheckoutRoute
  '/{-$lang}/products': typeof Char123LangChar125ProductsRouteWithChildren
  '/{-$lang}/terms': typeof Char123LangChar125TermsRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/account/forgot-password': typeof Char123LangChar125AccountForgotPasswordRoute
  '/{-$lang}/account/login': typeof Char123LangChar125AccountLoginRoute
  '/{-$lang}/account/register': typeof Char123LangChar125AccountRegisterRoute
  '/{-$lang}/account/wishlist': typeof Char123LangChar125AccountWishlistRoute
  '/{-$lang}/blog/$slug': typeof Char123LangChar125BlogSlugRoute
  '/{-$lang}/checkout_/return': typeof Char123LangChar125CheckoutReturnRoute
  '/{-$lang}/products/$productId': typeof Char123LangChar125ProductsProductIdRoute
  '/{-$lang}/account/': typeof Char123LangChar125AccountIndexRoute
  '/{-$lang}/blog/': typeof Char123LangChar125BlogIndexRoute
  '/{-$lang}/products/': typeof Char123LangChar125ProductsIndexRoute
  '/api/public/webhooks/paypal': typeof ApiPublicWebhooksPaypalRoute
  '/{-$lang}/account/orders/$orderId': typeof Char123LangChar125AccountOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/robots.txt'
    | '/sitemap-ar.xml'
    | '/sitemap-en.xml'
    | '/sitemap.xml'
    | '/{-$lang}/account'
    | '/{-$lang}/blog'
    | '/{-$lang}/cart'
    | '/{-$lang}/checkout'
    | '/{-$lang}/products'
    | '/{-$lang}/terms'
    | '/{-$lang}/'
    | '/{-$lang}/account/forgot-password'
    | '/{-$lang}/account/login'
    | '/{-$lang}/account/register'
    | '/{-$lang}/account/wishlist'
    | '/{-$lang}/blog/$slug'
    | '/{-$lang}/checkout/return'
    | '/{-$lang}/products/$productId'
    | '/{-$lang}/account/'
    | '/{-$lang}/blog/'
    | '/{-$lang}/products/'
    | '/api/public/webhooks/paypal'
    | '/{-$lang}/account/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/sitemap-ar.xml'
    | '/sitemap-en.xml'
    | '/sitemap.xml'
    | '/{-$lang}/cart'
    | '/{-$lang}/checkout'
    | '/{-$lang}/terms'
    | '/{-$lang}'
    | '/{-$lang}/account/forgot-password'
    | '/{-$lang}/account/login'
    | '/{-$lang}/account/register'
    | '/{-$lang}/account/wishlist'
    | '/{-$lang}/blog/$slug'
    | '/{-$lang}/checkout/return'
    | '/{-$lang}/products/$productId'
    | '/{-$lang}/account'
    | '/{-$lang}/blog'
    | '/{-$lang}/products'
    | '/api/public/webhooks/paypal'
    | '/{-$lang}/account/orders/$orderId'
  id:
    | '__root__'
    | '/robots.txt'
    | '/sitemap-ar.xml'
    | '/sitemap-en.xml'
    | '/sitemap.xml'
    | '/{-$lang}/account'
    | '/{-$lang}/blog'
    | '/{-$lang}/cart'
    | '/{-$lang}/checkout'
    | '/{-$lang}/products'
    | '/{-$lang}/terms'
    | '/{-$lang}/'
    | '/{-$lang}/account/forgot-password'
    | '/{-$lang}/account/login'
    | '/{-$lang}/account/register'
    | '/{-$lang}/account/wishlist'
    | '/{-$lang}/blog/$slug'
    | '/{-$lang}/checkout_/return'
    | '/{-$lang}/products/$productId'
    | '/{-$lang}/account/'
    | '/{-$lang}/blog/'
    | '/{-$lang}/products/'
    | '/api/public/webhooks/paypal'
    | '/{-$lang}/account/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapArDotxmlRoute: typeof SitemapArDotxmlRoute
  SitemapEnDotxmlRoute: typeof SitemapEnDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char123LangChar125AccountRoute: typeof Char123LangChar125AccountRouteWithChildren
  Char123LangChar125BlogRoute: typeof Char123LangChar125BlogRouteWithChildren
  Char123LangChar125CartRoute: typeof Char123LangChar125CartRoute
  Char123LangChar125CheckoutRoute: typeof Char123LangChar125CheckoutRoute
  Char123LangChar125ProductsRoute: typeof Char123LangChar125ProductsRouteWithChildren
  Char123LangChar125TermsRoute: typeof Char123LangChar125TermsRoute
  Char123LangChar125IndexRoute: typeof Char123LangChar125IndexRoute
  Char123LangChar125CheckoutReturnRoute: typeof Char123LangChar125CheckoutReturnRoute
  ApiPublicWebhooksPaypalRoute: typeof ApiPublicWebhooksPaypalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-en.xml': {
      id: '/sitemap-en.xml'
      path: '/sitemap-en.xml'
      fullPath: '/sitemap-en.xml'
      preLoaderRoute: typeof SitemapEnDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-ar.xml': {
      id: '/sitemap-ar.xml'
      path: '/sitemap-ar.xml'
      fullPath: '/sitemap-ar.xml'
      preLoaderRoute: typeof SitemapArDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/': {
      id: '/{-$lang}/'
      path: '/{-$lang}'
      fullPath: '/{-$lang}/'
      preLoaderRoute: typeof Char123LangChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/terms': {
      id: '/{-$lang}/terms'
      path: '/{-$lang}/terms'
      fullPath: '/{-$lang}/terms'
      preLoaderRoute: typeof Char123LangChar125TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/products': {
      id: '/{-$lang}/products'
      path: '/{-$lang}/products'
      fullPath: '/{-$lang}/products'
      preLoaderRoute: typeof Char123LangChar125ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/checkout': {
      id: '/{-$lang}/checkout'
      path: '/{-$lang}/checkout'
      fullPath: '/{-$lang}/checkout'
      preLoaderRoute: typeof Char123LangChar125CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/cart': {
      id: '/{-$lang}/cart'
      path: '/{-$lang}/cart'
      fullPath: '/{-$lang}/cart'
      preLoaderRoute: typeof Char123LangChar125CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/blog': {
      id: '/{-$lang}/blog'
      path: '/{-$lang}/blog'
      fullPath: '/{-$lang}/blog'
      preLoaderRoute: typeof Char123LangChar125BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/account': {
      id: '/{-$lang}/account'
      path: '/{-$lang}/account'
      fullPath: '/{-$lang}/account'
      preLoaderRoute: typeof Char123LangChar125AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/products/': {
      id: '/{-$lang}/products/'
      path: '/'
      fullPath: '/{-$lang}/products/'
      preLoaderRoute: typeof Char123LangChar125ProductsIndexRouteImport
      parentRoute: typeof Char123LangChar125ProductsRoute
    }
    '/{-$lang}/blog/': {
      id: '/{-$lang}/blog/'
      path: '/'
      fullPath: '/{-$lang}/blog/'
      preLoaderRoute: typeof Char123LangChar125BlogIndexRouteImport
      parentRoute: typeof Char123LangChar125BlogRoute
    }
    '/{-$lang}/account/': {
      id: '/{-$lang}/account/'
      path: '/'
      fullPath: '/{-$lang}/account/'
      preLoaderRoute: typeof Char123LangChar125AccountIndexRouteImport
      parentRoute: typeof Char123LangChar125AccountRoute
    }
    '/{-$lang}/products/$productId': {
      id: '/{-$lang}/products/$productId'
      path: '/$productId'
      fullPath: '/{-$lang}/products/$productId'
      preLoaderRoute: typeof Char123LangChar125ProductsProductIdRouteImport
      parentRoute: typeof Char123LangChar125ProductsRoute
    }
    '/{-$lang}/checkout_/return': {
      id: '/{-$lang}/checkout_/return'
      path: '/{-$lang}/checkout/return'
      fullPath: '/{-$lang}/checkout/return'
      preLoaderRoute: typeof Char123LangChar125CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/blog/$slug': {
      id: '/{-$lang}/blog/$slug'
      path: '/$slug'
      fullPath: '/{-$lang}/blog/$slug'
      preLoaderRoute: typeof Char123LangChar125BlogSlugRouteImport
      parentRoute: typeof Char123LangChar125BlogRoute
    }
    '/{-$lang}/account/wishlist': {
      id: '/{-$lang}/account/wishlist'
      path: '/wishlist'
      fullPath: '/{-$lang}/account/wishlist'
      preLoaderRoute: typeof Char123LangChar125AccountWishlistRouteImport
      parentRoute: typeof Char123LangChar125AccountRoute
    }
    '/{-$lang}/account/register': {
      id: '/{-$lang}/account/register'
      path: '/register'
      fullPath: '/{-$lang}/account/register'
      preLoaderRoute: typeof Char123LangChar125AccountRegisterRouteImport
      parentRoute: typeof Char123LangChar125AccountRoute
    }
    '/{-$lang}/account/login': {
      id: '/{-$lang}/account/login'
      path: '/login'
      fullPath: '/{-$lang}/account/login'
      preLoaderRoute: typeof Char123LangChar125AccountLoginRouteImport
      parentRoute: typeof Char123LangChar125AccountRoute
    }
    '/{-$lang}/account/forgot-password': {
      id: '/{-$lang}/account/forgot-password'
      path: '/forgot-password'
      fullPath: '/{-$lang}/account/forgot-password'
      preLoaderRoute: typeof Char123LangChar125AccountForgotPasswordRouteImport
      parentRoute: typeof Char123LangChar125AccountRoute
    }
    '/{-$lang}/account/orders/$orderId': {
      id: '/{-$lang}/account/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/{-$lang}/account/orders/$orderId'
      preLoaderRoute: typeof Char123LangChar125AccountOrdersOrderIdRouteImport
      parentRoute: typeof Char123LangChar125AccountRoute
    }
    '/api/public/webhooks/paypal': {
      id: '/api/public/webhooks/paypal'
      path: '/api/public/webhooks/paypal'
      fullPath: '/api/public/webhooks/paypal'
      preLoaderRoute: typeof ApiPublicWebhooksPaypalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Char123LangChar125AccountRouteChildren {
  Char123LangChar125AccountForgotPasswordRoute: typeof Char123LangChar125AccountForgotPasswordRoute
  Char123LangChar125AccountLoginRoute: typeof Char123LangChar125AccountLoginRoute
  Char123LangChar125AccountRegisterRoute: typeof Char123LangChar125AccountRegisterRoute
  Char123LangChar125AccountWishlistRoute: typeof Char123LangChar125AccountWishlistRoute
  Char123LangChar125AccountIndexRoute: typeof Char123LangChar125AccountIndexRoute
  Char123LangChar125AccountOrdersOrderIdRoute: typeof Char123LangChar125AccountOrdersOrderIdRoute
}

const Char123LangChar125AccountRouteChildren: Char123LangChar125AccountRouteChildren =
  {
    Char123LangChar125AccountForgotPasswordRoute:
      Char123LangChar125AccountForgotPasswordRoute,
    Char123LangChar125AccountLoginRoute: Char123LangChar125AccountLoginRoute,
    Char123LangChar125AccountRegisterRoute:
      Char123LangChar125AccountRegisterRoute,
    Char123LangChar125AccountWishlistRoute:
      Char123LangChar125AccountWishlistRoute,
    Char123LangChar125AccountIndexRoute: Char123LangChar125AccountIndexRoute,
    Char123LangChar125AccountOrdersOrderIdRoute:
      Char123LangChar125AccountOrdersOrderIdRoute,
  }

const Char123LangChar125AccountRouteWithChildren =
  Char123LangChar125AccountRoute._addFileChildren(
    Char123LangChar125AccountRouteChildren,
  )

interface Char123LangChar125BlogRouteChildren {
  Char123LangChar125BlogSlugRoute: typeof Char123LangChar125BlogSlugRoute
  Char123LangChar125BlogIndexRoute: typeof Char123LangChar125BlogIndexRoute
}

const Char123LangChar125BlogRouteChildren: Char123LangChar125BlogRouteChildren =
  {
    Char123LangChar125BlogSlugRoute: Char123LangChar125BlogSlugRoute,
    Char123LangChar125BlogIndexRoute: Char123LangChar125BlogIndexRoute,
  }

const Char123LangChar125BlogRouteWithChildren =
  Char123LangChar125BlogRoute._addFileChildren(
    Char123LangChar125BlogRouteChildren,
  )

interface Char123LangChar125ProductsRouteChildren {
  Char123LangChar125ProductsProductIdRoute: typeof Char123LangChar125ProductsProductIdRoute
  Char123LangChar125ProductsIndexRoute: typeof Char123LangChar125ProductsIndexRoute
}

const Char123LangChar125ProductsRouteChildren: Char123LangChar125ProductsRouteChildren =
  {
    Char123LangChar125ProductsProductIdRoute:
      Char123LangChar125ProductsProductIdRoute,
    Char123LangChar125ProductsIndexRoute: Char123LangChar125ProductsIndexRoute,
  }

const Char123LangChar125ProductsRouteWithChildren =
  Char123LangChar125ProductsRoute._addFileChildren(
    Char123LangChar125ProductsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapArDotxmlRoute: SitemapArDotxmlRoute,
  SitemapEnDotxmlRoute: SitemapEnDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char123LangChar125AccountRoute: Char123LangChar125AccountRouteWithChildren,
  Char123LangChar125BlogRoute: Char123LangChar125BlogRouteWithChildren,
  Char123LangChar125CartRoute: Char123LangChar125CartRoute,
  Char123LangChar125CheckoutRoute: Char123LangChar125CheckoutRoute,
  Char123LangChar125ProductsRoute: Char123LangChar125ProductsRouteWithChildren,
  Char123LangChar125TermsRoute: Char123LangChar125TermsRoute,
  Char123LangChar125IndexRoute: Char123LangChar125IndexRoute,
  Char123LangChar125CheckoutReturnRoute: Char123LangChar125CheckoutReturnRoute,
  ApiPublicWebhooksPaypalRoute: ApiPublicWebhooksPaypalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
